version: 2

defaults: &defaults
  docker:
    - image: canonicalwebteam/dev

jobs:
  python-lint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Lint python code
          command: yarn python-lint

workflows:
  version: 2
  build:
    jobs:
      - python-lint
